// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGCWcnZqPpCfDCA2LFTSxp7YAzaeEv5nk',
    appId: '1:550379194975:web:9c7340e1e56f5ea6c469ea',
    messagingSenderId: '550379194975',
    projectId: 'moya-44331',
    authDomain: 'moya-44331.firebaseapp.com',
    storageBucket: 'moya-44331.firebasestorage.app',
    measurementId: 'G-P1GXKH2VLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfU90VpG_a0wqpbwT0epw0GeLEjE48Rw',
    appId: '1:550379194975:android:453b0788442366b1c469ea',
    messagingSenderId: '550379194975',
    projectId: 'moya-44331',
    storageBucket: 'moya-44331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8aFpl-CuiOI-V6ut4L_Op8Q_l78If9ig',
    appId: '1:550379194975:ios:ecbef9e058a6a967c469ea',
    messagingSenderId: '550379194975',
    projectId: 'moya-44331',
    storageBucket: 'moya-44331.firebasestorage.app',
    iosBundleId: 'com.example.moya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8aFpl-CuiOI-V6ut4L_Op8Q_l78If9ig',
    appId: '1:550379194975:ios:ecbef9e058a6a967c469ea',
    messagingSenderId: '550379194975',
    projectId: 'moya-44331',
    storageBucket: 'moya-44331.firebasestorage.app',
    iosBundleId: 'com.example.moya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGCWcnZqPpCfDCA2LFTSxp7YAzaeEv5nk',
    appId: '1:550379194975:web:f5dd4c709b81c875c469ea',
    messagingSenderId: '550379194975',
    projectId: 'moya-44331',
    authDomain: 'moya-44331.firebaseapp.com',
    storageBucket: 'moya-44331.firebasestorage.app',
    measurementId: 'G-HDYXNHJ7MZ',
  );
}
